---
title: "Exercies 2 - Alon Godman & Ran Hassid"
output: html_notebook
---

# Q1 #

## 1 ##
### 1.1 ###

The Density Function is (1/(-log(p)))*(beta*(1-p)*exp(-beta*x))/(1-(1-p)*exp(-beta*x)).
```{r}
func_1.1 <- function(beta,p){
  CDF_1.1 <- function(x,beta,p){
      (-beta^2/log(p))*log((1-(1-p)*exp(-beta*x))/p)
  } # Lets compute the CDF of f(x).
  inverse_func_1.1 <- function(u,beta,p){
    -(log(1-((p/(1-p))*exp((u*log(p)))/-beta^2)))/beta
  } # Lets compute the inverse function: f(x)=u, u~U(0,1).
  U.1.1 <- runif(n = 10000,min = 0,max = 1) # Lets sample 10000 samples from U(0,1) distribution.
  X.1.1 <- inverse_func_1.1(U.1.1,beta,p) # For any u in U we compute the x value.
  F_x.1.1 <- CDF_1.1(X.1.1,beta,p) # For any x in X we compute the F(x) value.
  hist(F_x.1.1)
  summary(F_x.1.1)
}

func_1.1(2,0.5)
```

### 1.2 ###

### 1.3 ###

The Density Function is a*b*x^(a-1)*(1-x^a)^(b-1)
```{r}
func_1.3 <- function(a,b){
  CDF_1.3 <- function(x,a,b){
    (((1-x^a)^b)-1)
    } # Lets compute the CDF of f(x).
  inverse_func_1.3 <- function(u,a,b){
    (1-(u+1)^(1/b))^(1/a)
    } # Lets compute the inverse function: f(x)=u, u~U(0,1).
  U.1.3 <- runif(n = 10000,min = 0,max = 1) # Lets sample 10000 samples from U(0,1) distribution.
  X.1.3 <- inverse_func_1.3(U.1.3,a,b) # For any u in U we compute the x value.
  F_x.1.3 <- CDF_1.3(X.1.3,a,b) # For any x in X we compute the F(x) value.
  hist(F_x.1.3)
  summary(F_x.1.3)
  }

func_1.3(3,3)
```


